import type { EvVehicle } from "@/lib/compatibility/types";

const IMG_EV =
  "https://images.unsplash.com/photo-1593941707882-a5bba14938ca?w=900&h=600&fit=crop";

function v(
  partial: Omit<EvVehicle, "image" | "recommendedAccessories"> & {
    image?: string;
    recommendedAccessories?: string[];
  }
): EvVehicle {
  return {
    image: IMG_EV,
    recommendedAccessories: [
      "Cablu Type 2",
      "Protecție RCBO 32A",
      "Suport perete wallbox",
    ],
    ...partial,
  };
}

export const EV_VEHICLES: EvVehicle[] = [
  v({
    slug: "tesla-model-y",
    brand: "Tesla",
    model: "Model Y",
    yearFrom: 2022,
    batteryKwh: 75,
    acMaxKw: 11,
    dcMaxKw: 250,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2 mobil 7–11 kW",
    installationNote:
      "Trifazat 16A minim pentru 11 kW. Programare nocturnă recomandată.",
    relatedLanding: "/statie-incarcare-tesla",
  }),
  v({
    slug: "tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    yearFrom: 2019,
    batteryKwh: 60,
    acMaxKw: 11,
    dcMaxKw: 250,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2 mobil",
    installationNote: "Wallbox 11 kW trifazat — încărcare completă ~6 h.",
    relatedLanding: "/statie-incarcare-tesla",
  }),
  v({
    slug: "tesla-model-s",
    brand: "Tesla",
    model: "Model S",
    yearFrom: 2021,
    batteryKwh: 100,
    acMaxKw: 11,
    dcMaxKw: 250,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Baterie mare — 11 kW AC overnight este optim.",
    relatedLanding: "/statie-incarcare-tesla",
  }),
  v({
    slug: "tesla-model-x",
    brand: "Tesla",
    model: "Model X",
    yearFrom: 2021,
    batteryKwh: 100,
    acMaxKw: 11,
    dcMaxKw: 250,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "SUV greu — verificați circuit dedicat 16A/trifazat.",
    relatedLanding: "/statie-incarcare-tesla",
  }),
  v({
    slug: "bmw-i4",
    brand: "BMW",
    model: "i4",
    yearFrom: 2022,
    batteryKwh: 84,
    acMaxKw: 11,
    dcMaxKw: 205,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2 11 kW",
    installationNote:
      "11 kW trifazat standard BMW. OCPP opțional pentru firmă.",
    relatedLanding: "/statie-incarcare-bmw",
  }),
  v({
    slug: "bmw-ix",
    brand: "BMW",
    model: "iX",
    yearFrom: 2022,
    batteryKwh: 111,
    acMaxKw: 11,
    dcMaxKw: 195,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote:
      "Baterie 111 kWh — planificați încărcare nocturnă completă.",
    relatedLanding: "/statie-incarcare-bmw",
  }),
  v({
    slug: "bmw-i5",
    brand: "BMW",
    model: "i5",
    yearFrom: 2024,
    batteryKwh: 84,
    acMaxKw: 11,
    dcMaxKw: 205,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Identic i4 din punct de vedere AC — wallbox 11 kW.",
    relatedLanding: "/statie-incarcare-bmw",
  }),
  v({
    slug: "bmw-ix3",
    brand: "BMW",
    model: "iX3",
    yearFrom: 2021,
    batteryKwh: 80,
    acMaxKw: 11,
    dcMaxKw: 150,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "SUV compact — 11 kW acasă suficient.",
    relatedLanding: "/statie-incarcare-bmw",
  }),
  v({
    slug: "hyundai-kona-electric",
    brand: "Hyundai",
    model: "Kona Electric",
    yearFrom: 2021,
    batteryKwh: 64,
    acMaxKw: 11,
    dcMaxKw: 100,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2 7–11 kW",
    installationNote: "Urban SUV — wallbox 11 kW trifazat recomandat.",
    relatedLanding: "/statie-incarcare-hyundai",
  }),
  v({
    slug: "hyundai-ioniq-5",
    brand: "Hyundai",
    model: "Ioniq 5",
    yearFrom: 2022,
    batteryKwh: 77,
    acMaxKw: 11,
    dcMaxKw: 220,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "800V DC la public — acasă 11 kW AC standard.",
    relatedLanding: "/statie-incarcare-hyundai",
  }),
  v({
    slug: "hyundai-ioniq-6",
    brand: "Hyundai",
    model: "Ioniq 6",
    yearFrom: 2023,
    batteryKwh: 77,
    acMaxKw: 11,
    dcMaxKw: 220,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Sedan aerodinamic — încărcare completă ~7 h la 11 kW.",
    relatedLanding: "/statie-incarcare-hyundai",
  }),
  v({
    slug: "volkswagen-id3",
    brand: "Volkswagen",
    model: "ID.3",
    yearFrom: 2020,
    batteryKwh: 58,
    acMaxKw: 11,
    dcMaxKw: 170,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "MEB platform — 11 kW trifazat acasă.",
    relatedLanding: "/statie-incarcare-volkswagen",
  }),
  v({
    slug: "volkswagen-id4",
    brand: "Volkswagen",
    model: "ID.4",
    yearFrom: 2021,
    batteryKwh: 77,
    acMaxKw: 11,
    dcMaxKw: 170,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "SUV familie — wallbox 11 kW overnight.",
    relatedLanding: "/statie-incarcare-volkswagen",
  }),
  v({
    slug: "volkswagen-id5",
    brand: "Volkswagen",
    model: "ID.5",
    yearFrom: 2022,
    batteryKwh: 77,
    acMaxKw: 11,
    dcMaxKw: 170,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Coupe SUV ID — aceleași recomandări ca ID.4.",
    relatedLanding: "/statie-incarcare-volkswagen",
  }),
  v({
    slug: "volkswagen-id7",
    brand: "Volkswagen",
    model: "ID.7",
    yearFrom: 2024,
    batteryKwh: 86,
    acMaxKw: 11,
    dcMaxKw: 200,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote:
      "Sedan premium — 11 kW AC, opțional 22 kW dacă echipat.",
    relatedLanding: "/statie-incarcare-volkswagen",
  }),
  v({
    slug: "dacia-spring",
    brand: "Dacia",
    model: "Spring",
    yearFrom: 2021,
    batteryKwh: 27,
    acMaxKw: 7.4,
    dcMaxKw: 30,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "SINGLE",
    recommendedChargerKw: 7.4,
    recommendedHomeChargerKw: 7.4,
    recommendedPortableCharger: "Cablu Type 2 7,4 kW",
    installationNote:
      "Monofazat 32A — stația 22 kW NU accelerează încărcarea.",
    relatedLanding: "/statie-incarcare-dacia-spring",
  }),
  v({
    slug: "mercedes-eqa",
    brand: "Mercedes",
    model: "EQA",
    yearFrom: 2021,
    batteryKwh: 67,
    acMaxKw: 11,
    dcMaxKw: 100,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "EQ compact — 11 kW wallbox suficient.",
    relatedLanding: "/statie-incarcare-mercedes",
  }),
  v({
    slug: "mercedes-eqb",
    brand: "Mercedes",
    model: "EQB",
    yearFrom: 2022,
    batteryKwh: 67,
    acMaxKw: 11,
    dcMaxKw: 100,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "SUV EQ — instalare trifazat recomandată.",
    relatedLanding: "/statie-incarcare-mercedes",
  }),
  v({
    slug: "mercedes-eqs",
    brand: "Mercedes",
    model: "EQS",
    yearFrom: 2022,
    batteryKwh: 108,
    acMaxKw: 22,
    dcMaxKw: 200,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 22,
    recommendedHomeChargerKw: 22,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote:
      "22 kW AC opțional — necesită trifazat 32A+ dedicat.",
    relatedLanding: "/statie-incarcare-mercedes",
  }),
  v({
    slug: "kia-ev6",
    brand: "Kia",
    model: "EV6",
    yearFrom: 2022,
    batteryKwh: 77,
    acMaxKw: 11,
    dcMaxKw: 220,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Platformă E-GMP — 11 kW acasă.",
    relatedLanding: "/statie-incarcare-kia",
  }),
  v({
    slug: "kia-niro-ev",
    brand: "Kia",
    model: "Niro EV",
    yearFrom: 2022,
    batteryKwh: 65,
    acMaxKw: 11,
    dcMaxKw: 80,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Crossover urban — wallbox 11 kW.",
    relatedLanding: "/statie-incarcare-kia",
  }),
  v({
    slug: "kia-ev9",
    brand: "Kia",
    model: "EV9",
    yearFrom: 2024,
    batteryKwh: 99,
    acMaxKw: 11,
    dcMaxKw: 210,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "SUV mare 7 locuri — încărcare nocturnă esențială.",
    relatedLanding: "/statie-incarcare-kia",
  }),
  v({
    slug: "byd-atto-3",
    brand: "BYD",
    model: "Atto 3",
    yearFrom: 2023,
    batteryKwh: 60,
    acMaxKw: 11,
    dcMaxKw: 88,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "SUV compact BYD — 11 kW trifazat.",
    relatedLanding: "/statie-incarcare-byd",
  }),
  v({
    slug: "byd-dolphin",
    brand: "BYD",
    model: "Dolphin",
    yearFrom: 2024,
    batteryKwh: 45,
    acMaxKw: 7.4,
    dcMaxKw: 88,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "SINGLE",
    recommendedChargerKw: 7.4,
    recommendedHomeChargerKw: 7.4,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Urban — 7,4 kW monofazat ideal.",
    relatedLanding: "/statie-incarcare-byd",
  }),
  v({
    slug: "byd-seal",
    brand: "BYD",
    model: "Seal",
    yearFrom: 2024,
    batteryKwh: 82,
    acMaxKw: 11,
    dcMaxKw: 150,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Sedan sport — 11 kW AC standard.",
    relatedLanding: "/statie-incarcare-byd",
  }),
  v({
    slug: "audi-q4-etron",
    brand: "Audi",
    model: "Q4 e-tron",
    yearFrom: 2021,
    batteryKwh: 77,
    acMaxKw: 11,
    dcMaxKw: 135,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "MEB Audi — 11 kW wallbox.",
    relatedLanding: "/statie-incarcare-audi",
  }),
  v({
    slug: "audi-etron",
    brand: "Audi",
    model: "e-tron",
    yearFrom: 2019,
    batteryKwh: 95,
    acMaxKw: 22,
    dcMaxKw: 150,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 22,
    recommendedHomeChargerKw: 22,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "22 kW AC — stație trifazată 22 kW recomandată.",
    relatedLanding: "/statie-incarcare-audi",
  }),
  v({
    slug: "skoda-enyaq",
    brand: "Skoda",
    model: "Enyaq iV",
    yearFrom: 2021,
    batteryKwh: 77,
    acMaxKw: 11,
    dcMaxKw: 135,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Cel mai vândut SUV electric Skoda în RO.",
    relatedLanding: "/statie-incarcare-skoda",
  }),
  v({
    slug: "renault-zoe",
    brand: "Renault",
    model: "Zoe",
    yearFrom: 2020,
    batteryKwh: 52,
    acMaxKw: 22,
    dcMaxKw: 50,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 22,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote:
      "Zoe acceptă 22 kW AC — 11 kW suficient pentru uz zilnic.",
  }),
  v({
    slug: "peugeot-e-208",
    brand: "Peugeot",
    model: "e-208",
    yearFrom: 2020,
    batteryKwh: 50,
    acMaxKw: 11,
    dcMaxKw: 100,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Urban — wallbox 11 kW acasă.",
  }),
  v({
    slug: "ford-mustang-mach-e",
    brand: "Ford",
    model: "Mustang Mach-E",
    yearFrom: 2021,
    batteryKwh: 88,
    acMaxKw: 11,
    dcMaxKw: 150,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "SUV sport — 11 kW trifazat recomandat.",
  }),
  v({
    slug: "volvo-ex30",
    brand: "Volvo",
    model: "EX30",
    yearFrom: 2024,
    batteryKwh: 69,
    acMaxKw: 11,
    dcMaxKw: 153,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 11,
    recommendedHomeChargerKw: 11,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "Compact premium — wallbox 11 kW.",
  }),
  v({
    slug: "porsche-taycan",
    brand: "Porsche",
    model: "Taycan",
    yearFrom: 2020,
    batteryKwh: 93,
    acMaxKw: 22,
    dcMaxKw: 270,
    acConnector: "Type 2",
    dcConnector: "CCS2",
    phases: "THREE",
    recommendedChargerKw: 22,
    recommendedHomeChargerKw: 22,
    recommendedPortableCharger: "Cablu Type 2",
    installationNote: "22 kW AC + DC rapid — infrastructură premium.",
  }),
];

const BY_SLUG = new Map(EV_VEHICLES.map((item) => [item.slug, item]));

export function getAllVehicles(): EvVehicle[] {
  return EV_VEHICLES;
}

export function getVehicleBySlug(slug: string): EvVehicle | undefined {
  return BY_SLUG.get(slug);
}

export function getVehicleBrands(): string[] {
  return [...new Set(EV_VEHICLES.map((item) => item.brand))].sort();
}

export function getVehiclesByBrand(brand: string): EvVehicle[] {
  return EV_VEHICLES.filter((item) => item.brand === brand);
}

export function getRelatedVehicles(vehicle: EvVehicle, limit = 4): EvVehicle[] {
  const sameBrand = EV_VEHICLES.filter(
    (item) => item.brand === vehicle.brand && item.slug !== vehicle.slug
  );
  if (sameBrand.length >= limit) return sameBrand.slice(0, limit);

  const similarPower = EV_VEHICLES.filter(
    (item) =>
      item.slug !== vehicle.slug &&
      item.brand !== vehicle.brand &&
      Math.abs(
        item.recommendedHomeChargerKw - vehicle.recommendedHomeChargerKw
      ) <= 3.4
  );
  return [...sameBrand, ...similarPower].slice(0, limit);
}
