import type { CatalogProduct } from "@/types/catalog";

export const SEED_CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: "1",
    name: "ChargePro Home 7.4 kW",
    slug: "chargepro-home-7-4kw",
    shortDescription: "Stație wallbox monofazată pentru încărcare acasă.",
    description:
      "Stație de încărcare compactă, ideală pentru garaj sau curte. Instalare simplă, protecție IP54, conectivitate WiFi și aplicație mobilă pentru monitorizare consum.",
    price: 2899,
    compareAtPrice: 3299,
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938ca?w=800&h=600&fit=crop",
    category: "Stații AC",
    categorySlug: "statii-ac",
    brand: "ChargePro",
    brandSlug: "chargepro",
    powerKw: 7.4,
    phases: "SINGLE",
    connectorTypes: ["Type 2"],
    isFeatured: true,
    stock: 15,
    createdAt: "2026-01-15",
  },
  {
    id: "2",
    name: "ChargePro Pro 22 kW",
    slug: "chargepro-pro-22kw",
    shortDescription: "Performanță trifazată pentru flote și spații comerciale.",
    price: 5499,
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&h=600&fit=crop",
    category: "Stații AC",
    categorySlug: "statii-ac",
    brand: "ChargePro",
    brandSlug: "chargepro",
    powerKw: 22,
    phases: "THREE",
    connectorTypes: ["Type 2"],
    isFeatured: true,
    isNew: true,
    stock: 8,
    createdAt: "2026-03-01",
  },
  {
    id: "3",
    name: "VoltEdge DC 60 kW",
    slug: "voltedge-dc-60kw",
    shortDescription: "Încărcare rapidă DC pentru stații publice.",
    price: 89900,
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&h=600&fit=crop",
    category: "Stații DC",
    categorySlug: "statii-dc",
    brand: "VoltEdge",
    brandSlug: "voltedge",
    powerKw: 60,
    phases: "THREE",
    connectorTypes: ["CCS2"],
    isFeatured: true,
    stock: 3,
    createdAt: "2025-11-20",
  },
  {
    id: "4",
    name: "Cablu Type 2 — 7.5m",
    slug: "cablu-type2-7-5m",
    shortDescription: "Cablu premium Type 2, 32A, lungime 7.5 metri.",
    price: 649,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    category: "Accesorii",
    categorySlug: "accesorii",
    brand: "ChargePro",
    brandSlug: "chargepro",
    powerKw: 22,
    phases: "THREE",
    connectorTypes: ["Type 2"],
    stock: 42,
    createdAt: "2025-09-10",
  },
  {
    id: "5",
    name: "SmartBox OCPP Gateway",
    slug: "smartbox-ocpp-gateway",
    shortDescription: "Modul de management OCPP pentru stații existente.",
    price: 1899,
    compareAtPrice: 2199,
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&h=600&fit=crop",
    category: "Smart & OCPP",
    categorySlug: "smart-ocpp",
    brand: "ChargePro",
    brandSlug: "chargepro",
    powerKw: 0,
    phases: "SINGLE",
    connectorTypes: [],
    isNew: true,
    stock: 20,
    createdAt: "2026-04-05",
  },
  {
    id: "6",
    name: "ChargePro Wall 11 kW",
    slug: "chargepro-wall-11kw",
    shortDescription: "Design premium, montaj pe perete, încărcare rapidă.",
    price: 3799,
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938ca?w=800&h=600&fit=crop",
    category: "Stații AC",
    categorySlug: "statii-ac",
    brand: "ChargePro",
    brandSlug: "chargepro",
    powerKw: 11,
    phases: "THREE",
    connectorTypes: ["Type 2"],
    stock: 12,
    createdAt: "2026-02-18",
  },
  {
    id: "7",
    name: "EcoWatt Home 7.4 kW",
    slug: "ecowatt-home-7-4kw",
    shortDescription: "Soluție economică pentru încărcare rezidențială.",
    price: 2499,
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938ca?w=800&h=600&fit=crop",
    category: "Stații AC",
    categorySlug: "statii-ac",
    brand: "EcoWatt",
    brandSlug: "ecowatt",
    powerKw: 7.4,
    phases: "SINGLE",
    connectorTypes: ["Type 2"],
    stock: 25,
    createdAt: "2025-12-01",
  },
  {
    id: "8",
    name: "EcoWatt Business 22 kW",
    slug: "ecowatt-business-22kw",
    shortDescription: "Stație trifazată pentru parcări de firmă.",
    price: 4999,
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&h=600&fit=crop",
    category: "Stații AC",
    categorySlug: "statii-ac",
    brand: "EcoWatt",
    brandSlug: "ecowatt",
    powerKw: 22,
    phases: "THREE",
    connectorTypes: ["Type 2"],
    isFeatured: true,
    stock: 10,
    createdAt: "2026-01-28",
  },
  {
    id: "9",
    name: "VoltEdge DC 120 kW",
    slug: "voltedge-dc-120kw",
    shortDescription: "Ultra-fast charging pentru hub-uri de mobilitate.",
    price: 145000,
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&h=600&fit=crop",
    category: "Stații DC",
    categorySlug: "statii-dc",
    brand: "VoltEdge",
    brandSlug: "voltedge",
    powerKw: 120,
    phases: "THREE",
    connectorTypes: ["CCS2", "CHAdeMO"],
    stock: 2,
    createdAt: "2025-10-15",
  },
  {
    id: "10",
    name: "PowerLink Compact 11 kW",
    slug: "powerlink-compact-11kw",
    shortDescription: "Wallbox compact cu RFID și app mobilă.",
    price: 3299,
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938ca?w=800&h=600&fit=crop",
    category: "Stații AC",
    categorySlug: "statii-ac",
    brand: "PowerLink",
    brandSlug: "powerlink",
    powerKw: 11,
    phases: "THREE",
    connectorTypes: ["Type 2"],
    stock: 18,
    createdAt: "2026-02-01",
  },
  {
    id: "11",
    name: "SmartCharge Pro OCPP",
    slug: "smartcharge-pro-ocpp",
    shortDescription: "Stație inteligentă cu OCPP 2.0.1 și load balancing.",
    price: 4299,
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&h=600&fit=crop",
    category: "Smart & OCPP",
    categorySlug: "smart-ocpp",
    brand: "SmartCharge",
    brandSlug: "smartcharge",
    powerKw: 11,
    phases: "THREE",
    connectorTypes: ["Type 2"],
    isNew: true,
    stock: 14,
    createdAt: "2026-05-01",
  },
  {
    id: "12",
    name: "GridFlow DC 40 kW",
    slug: "gridflow-dc-40kw",
    shortDescription: "Stație DC dual-port pentru retail și hospitality.",
    price: 65900,
    image: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&h=600&fit=crop",
    category: "Stații DC",
    categorySlug: "statii-dc",
    brand: "GridFlow",
    brandSlug: "gridflow",
    powerKw: 40,
    phases: "THREE",
    connectorTypes: ["CCS2"],
    stock: 5,
    createdAt: "2025-08-22",
  },
  {
    id: "13",
    name: "Protecție RCBO 32A",
    slug: "protectie-rcbo-32a",
    shortDescription: "Disjunctor diferențial pentru instalații EV.",
    price: 389,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    category: "Accesorii",
    categorySlug: "accesorii",
    brand: "PowerLink",
    brandSlug: "powerlink",
    powerKw: 0,
    phases: "SINGLE",
    connectorTypes: [],
    stock: 60,
    createdAt: "2025-07-10",
  },
  {
    id: "14",
    name: "Suport perete reglabil",
    slug: "suport-perete-reglabil",
    shortDescription: "Suport universal pentru stații wallbox.",
    price: 279,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    category: "Accesorii",
    categorySlug: "accesorii",
    brand: "ChargePro",
    brandSlug: "chargepro",
    powerKw: 0,
    phases: "SINGLE",
    connectorTypes: [],
    stock: 35,
    createdAt: "2025-06-15",
  },
  {
    id: "15",
    name: "ChargePro Tesla Adapter",
    slug: "chargepro-tesla-adapter",
    shortDescription: "Adaptor Type 2 — Tesla pentru stații publice.",
    price: 449,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    category: "Accesorii",
    categorySlug: "accesorii",
    brand: "ChargePro",
    brandSlug: "chargepro",
    powerKw: 0,
    phases: "SINGLE",
    connectorTypes: ["Tesla", "Type 2"],
    stock: 28,
    createdAt: "2026-03-20",
  },
  {
    id: "16",
    name: "SmartCharge Fleet Hub",
    slug: "smartcharge-fleet-hub",
    shortDescription: "Platformă cloud pentru management flote EV.",
    price: 2999,
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&h=600&fit=crop",
    category: "Smart & OCPP",
    categorySlug: "smart-ocpp",
    brand: "SmartCharge",
    brandSlug: "smartcharge",
    powerKw: 0,
    phases: "SINGLE",
    connectorTypes: [],
    isFeatured: true,
    stock: 50,
    createdAt: "2026-04-12",
  },
  {
    id: "17",
    name: "GridFlow AC 7.4 kW",
    slug: "gridflow-ac-7-4kw",
    shortDescription: "Wallbox accesibil cu protecție IP65.",
    price: 2199,
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938ca?w=800&h=600&fit=crop",
    category: "Stații AC",
    categorySlug: "statii-ac",
    brand: "GridFlow",
    brandSlug: "gridflow",
    powerKw: 7.4,
    phases: "SINGLE",
    connectorTypes: ["Type 2"],
    stock: 22,
    createdAt: "2025-11-05",
  },
  {
    id: "18",
    name: "VoltEdge DC 30 kW",
    slug: "voltedge-dc-30kw",
    shortDescription: "Soluție DC compactă pentru spații comerciale mici.",
    price: 45900,
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&h=600&fit=crop",
    category: "Stații DC",
    categorySlug: "statii-dc",
    brand: "VoltEdge",
    brandSlug: "voltedge",
    powerKw: 30,
    phases: "THREE",
    connectorTypes: ["CCS2"],
    stock: 7,
    createdAt: "2026-01-08",
  },
];
